linuxcnc-ethercat/linuxcnc-ethercat

.github/workflows/ci.yml, .gitignore, .pre-commit-config.yaml
First pass at simplifying the number of apt packages installed; this seems to lop a couple minutes off of the build time.  Verified with and without the cache.
Also added a YAML link/format pre-commit hook.  I've had way too many issues with malformed `ci.yml` files; this should prevent them.
This is part of issue #3.
=> Simplify CI dependencies and add YAML pre-commit hook

.github/workflows/ci.yml
Break the LinuxCNC and Ethercat Master builds out into their own jobs in the CI process.  This lets them be cached individually and (at least potentially) build in parallel.  This *also* allows me to skip installing all of LinuxCNC's `apt` dependencies as part of the LinuxCNC-Ethercat build process; this drops the runtime down to ~42 seconds, which is probably reasonable.
Also part of issue #3
=> Parallelize workflows

.clang-format, CONTRIBUTING
Minor updates to the CONTRIBUTING doc, and add the default clang-format config discussed in issue #3.
I'm not opposed to changing the config, but it's good to have *something* in place.
=> Update CONTRIBUTING and add clang-format default

.github/workflows/ci.yml, .github/workflows/release.yml
Beginnings of actions for creating Debian packages.
This is kind of a mess at the moment, and almost certainly doesn't work right.  It's certainly never actually managed to spit out a release yet, although in its current incarnation it only runs after merging.  Or at least I think it does.
=> Add CI support for creating Debian packages

.github/workflows/release.yml
What this is supposed to do: automatically cut releases based on the PR descriptions.
What I *want* to have happen is to have the semantic-release action cut new releases as directed by PR descriptions, and then once that happens to update the Debian changelog and build a full set of Debian packages.
The odds of this actually working in its current state is slim., and when it does the Debian release process will almost certainly break.  Unfortunately, I kind of need to *actually merge PRs* in order to test this, so I'll be doing a short sequence of minor changes.
=> Add semantic-release to release workflow

.pre-commit-config.yaml
Since we're using yamlfmt after running yamllint, there's no real reason for it to be hyper-strict.  It's currently rejecting files due to blank lines, etc, which yamlfmt will fix anyway.
=> Switch yamllint to relaxed mode

.github/workflows/release.yml
Allow the job that updates debian/changelog to write back to Git.
=> Add write permissions to release workflow

.github/workflows/release.yml, debian/control
It looks like the EtherLab / Ethercat Master / whatever archive in OpenSuSE's build system is the defacto standard for .debs for the Ethercat libs that we need, so let's try using those.
#36
=> Add bone11111's opensuse .deb archive for EtherLab, and try building with that.

.github/workflows/release.yml
We're missing `curl` in the `.deb` build pipeline.  Install it before use.
Issue #36
=> release: add curl

.github/workflows/release.yml
Seeing transient failures with Debian 11, and Debian 12 is almost certainly broken, so concentrating on Debian 10 and Unstable for now.
Issue #36
=> release: Temporarily disable bookworm and bullseye .deb builds

.github/workflows/release.yml
Remove Debian Unstable from the list of images that we build for.  It's *also* failing randomly.  Concentrate on buster for now.
Gbp-Dch: ignore
Issue: #36
=> release: disable sid

.github/workflows/release.yml
Builds fail with debuild missing, so install the package that provides it.
Gbp-Dch: ignore
Issue: #36
=> release: install devscripts

.pre-commit-config.yaml
This verifies that commit messages are in the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format, which should give some structure to changelogs and release notes.
Each commit message should start with a type (see below), an optional scope in parenthesis, a colon, and then a short description of the change.
Examples:
- build: add conventional-commit pre-commit hook
- ci: fix broken workflow
- fix(el_1xxx): add support for EL1111
Types currently supported:
- build
- ci
- docs
- feat
- fix
- perf
- revert
- style
- test
The `feat` and `fix` types are special; a commit with `fix` will trigger a new version release (so we'll go from v1.0.0 to v1.0.1, etc).  Commits with `feat` will trigger a new minor release (v1.0.0 to v1.1.0, etc).  In general, any change to `.c` …
=> build: add conventional-commit pre-commit hook

.github/workflows/release.yml
=> ci: only run Debian changelog updater if a new version is being cut.

.pre-commit-config.yaml, debian/gbp.conf
In an ideal world, this will make `gbp dch` (called by the Debian Changelog action) actually pick up the release version from Git. 
Issue: #36
=> ci: Add gbp.conf to try to match Debian versions with GH release versions

TODO
This is a more-or-less bogus change, removing an 8 year old TODO file.  It's marked as 'fix' so that it triggers the release workflow, so I can verify that the deb release process works.
Issue: #36
=> fix(test): Remove TODO file

.github/workflows/release.yml
Trigger another semi-bogus release.  This changes the release workflow to only run on the branch, not on the push request.
=> fix(test): Only run the release process on the pull_request, not on the push.

.github/workflows/debian.yml, .github/workflows/release.yml
A few things:
- Merge the two jobs in `release.yml`, because they ran one after another and there was no point in making things more complicated than they had to be.
- Add a conditional to `Patch debian/changelog` so that it only runs if the semantic release step produces a value in its `changelog` output.  Reading the code, I *think* this will only be set if it ran and created a release.  This is surprisingly poorly documented.
- Rename the Debian release workflow; it was named "Release process" before, which was Confusing.
- Allow (for now) manual triggers of the release and Debian workflows.
Issue: #36
=> ci: more work on releases and debian building

.github/workflows/release.yml
The pi-top debian/changelog action didn't make it easy to control the version explicitly; it may
actually be easier to just run `gbp dch` directly than using their action anyway.
Issue: #36
=> ci: switch to using gbp-dch directly so we can control the generated version number

documentation/DEVICES.md, scripts/devicetable/devicetable.go
Also, ignore emacs backup files, and make sure that the table is sorted
by filename.
Issue #7
=> docs: Update device table

examples/testbench/ethercat.xml, src/Kbuild, src/lcec.h, src/lcec_el1xxx.c, src/lcec_main.c
Beginning of removing the global types[] list in `lcec_main.c` and
moving the code into individual drivers.  This will make patching less
complicated as it'll be one fewer file to edit when adding new drivers.
The goal is to be able to simply drop a pair of `lcec_FOO.[ch]` files
into `src/` and have them compile and work.  We're not there quite yet.
Current status:
- added code for defining types in `lcec_main.c` via a linked list as well as the static `types` array.
- added code in `lcec_main.c` for adding types to the the lined list dynamically.
- added a macro in `lcec.h` that calls the add-to-linked-list code before `main()` runs.
- moved all of the EL1xxx types `lcec_el1xxx` out of `lcec_main.c` and into `lcec_el1xxx.c`.
- added a `name` field to `lcec_typelist_t` and populated it …
=> build: Move types[] from lcec_main into individual drivers

src/Kbuild, src/lcec.h, src/lcec_devicelist.c, src/lcec_ethercat.c, src/lcec_main.c, src/lcec_pins.c, src/user.mk
This modifies the build system to get lcec_conf to link to all of the
drivers.  This will make it possible to get rid of `slaveTypes[]` in
`lcec_conf.c`, once we've dealt with all of the slave*Params.
Issue #35
=> build: first round of work to unify device lists

src/.clang-format, src/devices/.clang-format
This will make running `clang-format` easier and less trouble-prone.
=> build: symlink .clang-format into source dirs

.clang-format
80 leads to too much ugly wrapping.
=> build: Change clang style to allow 120 character lines

src/devices/lcec_generic.c
From https://github.com/sittner/linuxcnc-ethercat/issues/98, it looks
like we should be sign-extending reads of 8 or 16 bit signed values, and
we aren't doing that when the bit offset is nonzero.
=> fix(generic): sign-extend short, offset signed reads

documentation/DEVICES.md, scripts/devicetable/devicetable.go
Show the device driver name (`el3xxx`) instead of repeating the device
name (`EL3001`).
=> docs: Update device table format

documentation/DEVICES.md, documentation/devices/EK1100.yml, documentation/devices/EK1101.yml, documentation/devices/EK1110.yml, documentation/devices/EK1122.yml, documentation/devices/EP1122.yml, src/devices/lcec_passive.c, src/devices/lcec_passive.h, src/lcec_devicelist.c
This lets me move EK1100 and friends out of `lcec_devicelist.c`, which lets me delete the last remnants of `types[]` in that file.
This is intended to  be used for passive Ethercat devices, where we want to be able to list them in `ethercat.xml` for whatever reason, but they don't actually have PDOs or do anything.  We probably shouldn't have added the EKxxxx devices in the first place, but they're there now, and this should be cleaner.
=> build: create a "passive" driver.

src/Makefile
Otherwise DESTDIR does not work well...
=> build: create realtime dir on install

Makefile, src/Makefile, src/Makefile.clean
Running `make clean` on an already cleaned working dir fails because config.mk cannot be found.
```
root@8579ec95b724:/linuxcnc-ethercat# dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package linuxcnc-ethercat
dpkg-buildpackage: info: source version 0.9.16
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Scott Laird <scott@sigkill.org>
dpkg-buildpackage: info: host architecture amd64
dpkg-source --before-build .
debian/rules clean
dh clean 
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dh_auto_clean
dh_auto_clean: warning: Compatibility levels before 10 are deprecated (level 9 in use)
make -j1 clean
make[1]: Entering directory '/linuxcnc-ethercat'
make[2]: Entering directory '/linuxcnc-ethercat/src' …
```
=> build: Fix clean target

src/devices/lcec_generic.c, src/lcec_conf.c, src/lcec_conf.h
To use this, declare a PDO in `ethercat.xml` with
`halType="float-double-ieee"`.
This is currently *completely* untested.  It compiles.  That's all I can
promise.
Issue #115
=> feat(generic): Preliminary support for 64-bit floats

src/devices/lcec_generic.c, tests/haltest.sh, tests/test2.xml
=> fix(generic): Un-break generic in lcec_conf

src/lcec_conf.c, tests/haltest.sh, tests/test2.xml
Another dumb bug, hopefully this is enough to get generic support working.
To help with that, I changed a pair of EL1018 / EL2008s from using the el1xxx/el2xxx drivers to using the generic drivers, and added an extra wire or two.  My test suite now verifies that I can talk to devices via generic *and* that at least *some* PDOs work correctly.
Issues: #115, #135
Fixes: #145
=> fix(generic): Fix additional generic problems

src/devices/lcec_el3xxx.c, src/lcec.h, src/lcec_main.c
Revert one of the changes from #140; adding `channels` to `lcec_slave_t` and `lcec_typelist_t` doesn't really work very well, because we have a number of devices with multiple types of channels.  For instance, the EK18xx modules have various numbers of input and output ports.  The EK1814 that I have has 4 of each, but they're not all balanced like that.
Instead, this moves `channels` to `hal_data`, which is under driver control and is passed around widely already.  Since the driver controls it, we could add `input_channels` and `output_channels` where they make sense, or whatever makes sense for each driver.
=> refactor(el3xxx): Move channels into hal_data

src/devices/lcec_el5002.c
=> fix(el5002): Add additional hardware

src/devices/lcec_el5032.c
=> fix(el5032): Add additional hardware

src/devices/lcec_el5101.c
=> fix(el5101): Add additional hardware

src/devices/lcec_el5151.c
=> fix(el5151): Add additional hardware

src/devices/lcec_el6090.c
=> fix(el6090): Add additional hardware

src/devices/lcec_class_din.c, src/devices/lcec_class_din.h, src/devices/lcec_el1xxx.c
This creates a generic `lcec_class_din` with 3 function that can be used to implement a generic digital-input pin given a slave and PDO.  The API doesn't currently give any way to change the names of pins, other than an integer provided.  So, you can have `lcec.0.XX.din-0`, but you can't currently have `lcec.0.XX.sparkly-din-0`.  It'd be easy enough to add (add a new variant of `lcec_din_register_pin` that takes a name, and then reimplement `lcec_din_register_pin` in terms of the new function.
This moves `lcec_el1xxx.c` to use the new framework.  It's not a giant win here, but it'll make implementing random in/out devices (like the EK1814 and some of the EP modules, which *love* to put digital in/outs on random unused M12 pins) cleaner.
Issue: #42
=> refactor: create lcec_class_din and move el1xxx to use it

src/devices/lcec_el1859.c, tests/haltest.sh
This continues the stream of moving EL1xxx and EL2xxx drivers to use the new `lcec_class_din` and `lcec_class_dout` code, which started in #189.
Initially, this code was failing even the simplest tests.  Rolling back to the earlier `el1859` code didn't help.  Testing with a multimeter showed 0V on all output pins.  Bad module?  Nope--I'd used all of the current on the bus, and it was refusing to turn on.  I added an EL9410 just before this, and everything magically started passing.
Issue #42
=> refactor: move el1859 to use class_din/dout

documentation/DEVICES.md, documentation/devices/EL1252.yml, src/devices/lcec_el1252.c, src/devices/lcec_el1252.h
This moves the EL1252 driver to use the `lcec_class_din` framework from #189.  It removes a bunch of functionality that was never actually finished, including reading timestamps, but the code is *much* less complex now.
Note that the PDO addresses are different from other el1xxx devices.
Issue: #42
=> refactor: move el1252 driver to use class_din

src/devices/lcec_class_din.c, src/devices/lcec_class_dout.c, src/devices/lcec_el1859.c
Yeah, so it turns out that you can have the world's best test suite, but when you rsync your code into the wrong directory and still run the old code, it doesn't actually do you much good.
There were several problems with digital outputs with this week's `class_dout`:
- The pins were registered as going the wrong direction.
- `invert` was registered as a pin, not a param.
- Because it was a half-pin, half-param, it had about a 50% chance of setting the wrong output value.
- Also, the EL1859's output pins are actually based at 0x7080, not 0x7000, so the EL1859 driver stopped working.  Which is embarrassing, because I have one here.
Anyway, this should fix the known bugs, *and* add a framework for adding the remaining EP23* and EK18* devices.
Issue: #42
=> fix(el1859): Fix multiple digital out problems

src/devices/lcec_class_din.c, src/devices/lcec_class_din.h, src/devices/lcec_class_dout.c, src/devices/lcec_class_dout.h, src/devices/lcec_digitalcombo.c, src/devices/lcec_el1xxx.c, src/devices/lcec_el2xxx.c
Just a cleanup, keeping nomenclature clean before it becomes more widely used.
=> refactor: rename din/dout "pin" to "channel"

documentation/el7041.md, documentation/index.md, src/devices/lcec_el7041.c, src/devices/lcec_el7041.h, src/lcec.h, src/lcec_ethercat.c, tests/test2.xml
The goal here is to be able to control all of the settings for the EL7041 via `<modParams>` and not need explicit SDO tweaking.
Also includes the start at EL7041 documentation.
This includes a fix for #243.  It adds a set of `lcec_write_sdo()` functions that will fail fast when the SDO isn't correct.  The same basic fix will need to be applied to other users of `ecrt_slave_config_sdo*`.
=> feat(el7041): Add modparams for stepper config settings

src/devices/lcec_deasda.c, src/devices/lcec_el3xxx.c, src/devices/lcec_el5002.c, src/devices/lcec_el70x1.c, src/devices/lcec_el7211.c, src/devices/lcec_el7411.c, src/devices/lcec_omrg5.c, src/lcec.h, src/lcec_ethercat.c
Right now, attempts to write bogus values to SDOs aren't actually caught until after the device is started, which is too late for proper error handling.  This changes the way that SDOs are set, allowing us to catch bad SDOs immediately.  Verified w/ EL7041.
This should fix issue #243 for all drivers.
=> fix: Add SDO error handling

src/devices/lcec_class_ain.c, src/devices/lcec_class_ain.h, src/devices/lcec_el3xxx.c
This implements `lcec_class_ain`, similar to `lcec_class_din`.  The goal is to encapsulate all of the analog input-specific logic into a library that can be reused across multiple devices, such as `EP*` devices with both input and output ports.
This is still a work in progress. It's only lightly tested, but it passes my test suite.  It probably has too many options, but it's intended to be able to be used as part of `lcec_el3xxx`, as well as all of the random EP devices that have multiple port types, like the [EP4314](http://beckhoff.com/EP4314).  It should also be usable with non-Beckhoff devices, see the (pending) easyio driver.
=> feat(class_ain): Create new analog input class

documentation/deasda.md, src/devices/lcec_deasda.c, src/devices/lcec_deasda.h
Added PID config for Delta ASDA B3 drives based on ESI file comparison and PID 6080. I do not have a B3 but expect this to work just fine.
Relates to #248
=> fix(DeASDA): Add Support for B3 (untested)

src/lcec_main.c
`ecrt_slave_config_sdo` is asynchronous and doesn't return errors immediately.  Switch to using `lcec_write_sdo`, which *will* trigger an immediate error.
=> fix(main): Use lcec_write_sdo when setting SDOs from XML

src/devices/lcec_el4xxx.c
Okay, this was dumb, somehow I overlapped the "use subindex 11" flag with the "number of channels" range.  The upshot is that all EL4xx1 devices (really all devices with odd numbers of ports, but that's only the xxx1 variant, I think) are flagged as using `0x7000:11` instead of `0x7000:01` for outputs, which doesn't work at all.
Fixes #257
=> fix(el4xxx): Fix EL4xx1 devices

src/Makefile, src/devices/lcec_el3xxx.c, src/lcec.h, src/lcec_lookup.c
A lot of `<modParam>`s really want to provide a string value, which then maps onto a specific integer for setting an SDO.  For example, with `el3xxx`, there is a list of known temperature sensors, used to configure the hardware so that it returns the correct value for the type of sensor attached.  Instead of making the user look up which numeric code is used for Pt1000 sensors in a 300 page PDF, they can just say `<modParam name="sensor" value="Pt1000"/>` and the code does the lookup for them.
This pattern keeps getting repeated all over the place, so instead of re-implementing lookups everywhere, I wrote a shared implementation.
There are 2 flavors, string->int and string->double.  Each flavor has 2 lookup functions, one that is case-sensitive and once that is case-insensitive.  In all 4 …
=> feat(lookup): Add a generic lookup table for making modParams easier

documentation/devices/EL3102.yml, documentation/devices/EL3112.yml, documentation/devices/EL3122.yml, documentation/devices/EL3142.yml, documentation/devices/EL3152.yml, documentation/devices/EL3162.yml, documentation/devices/EL3182.yml, src/devices/lcec_el31x2.c, src/devices/lcec_el31x2.h, src/lcec_lookup.c
It turns out that the EL31x2 devices *aren't* the same as the rest of the EL3xxx family.   They use totally different PDOs.
Fixes #258
=> fix(el31x2): revert EL31x2 to old driver

.github/workflows/ci.yml, .gitignore, Makefile, src/Makefile, src/Makefile.clean, src/tests/test_lookup.c, src/tests/tests.h
Hey, look, it's preprocessor abuse day!
This adds a few tests in `src/tests`, enough `make` magic to make `make test` run them all, and updates the CI workflow to trigger `make test`.  It also removes the unused debian prep CI step, which should speed things up a bit.
Fixes #265
=> test: Add C test harness and lookup tests

src/Makefile, src/devices/lcec_el7041.c, src/lcec.h, src/lcec_devicelist.c
This does a few minor things:
- Removed 2 unused vars
- Adds a check for failed memory allocation that I'd missed earlier.
- Adds a few attributes to `lcec.h`, which should slightly improve static analysis in the future.
- Adds a commented-out option to the Makefile to enable `-fanalyzer`.  This is GCC's static analyzer, which tries to point out code bugs like not checking for failed malloc, etc.
I've waved both GCC and clang's analyzers over the code at this point, and they're both clean.  Neither really had anything exciting to say, but they caught a handful of unused vars and a few errors with error handling.
=> chore: make -fanalyzer happier

src/devices/lcec_class_din.c, src/devices/lcec_class_din.h, src/devices/lcec_class_dout.c, src/devices/lcec_class_dout.h
Add support for overriding the naming of `lcec_class_din` and `lcec_class_dout` pins.  By default, they're named `din-<ID>` and `dout-<ID>`, but a function is provided for providing the name directly.
Also support "packed" din/dout channels.  In this case, a packed channel is one where multiple channels share a single PDO entry on the slave, one per bit.  So, maybe bit 0 is `din-0`, bit 1 is `din-1`, and so forth.  They're registered using a new `_packed()` registration function, but otherwise work identically.
This builds and runs, but isn't fully tested yet.
This is a bit of a hack, but *should* work correctly.  I think.
Fixes #249
=> feat(din/dout): Digital in/out improvements

src/devices/lcec_el5102.c
This is for https://forum.linuxcnc.org/ethercat/35591-beckhoff-ethercat-64-with-bit-linuxcnc-how-to-install?start=290#294112; it *probably* doesn't work right as-is, but it compiles cleanly, and it's closer than the EL5101 driver is.  Hopefully we can get feedback and fix a few bugs quickly, leading to a working driver.
=> feat(el5102): Add untested driver for Beckhoff EL5102

src/devices/lcec_el5102.c
Apparently the EL5102's default PDOs don't include at least frequency and probably period.  I'm not sure if this is a bug in the Etherlab master (maybe?) or a bug in my understanding of how PDO mapping works (*completely* possible), as the [ESI data](https://linuxcnc-ethercat.github.io/esi-data/devices/EL5102) shows those mapped via a different PDO setup.
In any case, they're not going to work unless we write more code, so for now I've disabled them.
=> fix(el5102): Disable frequency and period metrics

documentation/cia402.md, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_rtec.c, src/lcec.h, src/lcec_ethercat.c, tests/scottlaird-lcectest1/haltest.sh
This exports object 0x6502 ("supported modes") as pin `srv-supported-modes` 
It also breaks out the standard modes into their own boolean pins, so higher-level code can check for feature support without doing bit math:
- `srv-supports-mode-csp`
- `srv-supports-mode-cst`
- `srv-supports-mode-csv`
- `srv-supports-mode-hm`
- `srv-supports-mode-ip`
- `srv-supports-mode-pp`
- `srv-supports-mode-pv`
- `srv-supports-mode-tq`
- `srv-supports-mode-vl`
Issue #180
=> feat(cia402): Add supported modes pins

src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_rtec.c, src/tests/test_cia402.c, tests/scottlaird-lcectest1/haltest.sh
These mostly make sense to modify on the fly, so they should be pins, not modparams.  This pulls in the hardware's current values at startup, so we should have sane defaults to work with.
This also renumbers modParams and changes things so that we can support 8 axes, not just 4.  I'm hoping to have a 6-axis test device on hand later this week.
Issue #180
=> feat(cia402): Move profile and homing settings from modParams to pins

src/devices/lcec_class_cia402.c, src/lcec.h, src/lcec_ethercat.c
The goal of this is to make every optional object basically identical, or as close as identical as possible.  It pulls index and subindex definitions into a set of `#define`s at the top and then references those from inside of `MAP_OPTIONAL_PDO()` and friends.  This should make adding additional optional PDOs (for `csv`, `cst`, `tq`, and `vl` modes, at a minimum) much less complicated and more consistent.
There is one remaining irritation here:
- The `OPTIONAL_PIN_x()` macros take a `var_name` and a `pin_name` parameter.  In all cases, the two are identical, except `var_name` uses underscores and `pin_name` uses dashes.  We could probably just use `# var_name` and then swap `_` for `-` later.
I'm not sure if that is worth bothering with, frankly.
Issue #180
=> refactor(cia402): Consolidate optional object handling

.github/workflows/ci.yml, .gitignore, debian/control, src/Makefile, src/configgen/devicelist.go, src/configgen/drivers/drivers.go, src/configgen/go.mod, src/configgen/go.sum, src/configgen/lcec_configgen.go
This is still a WIP.  It creates `lcec_configgen`, which can produce a config XML file based on data from `ethercat slaves`, `ethercat sdos`, and the list of supported VID:PID devices for each driver.
This is particularly focused on CiA 402 devices for now, because they have so many modParams that can enable additional features, but it should be able to ID pretty much any hardware that we know about.  It's still a work in progress, but here's what I get running it on my test box:
```xml
<masters>
<master idx="0">
<slave idx="0" type="EK1100" name="D1"/>
<slave idx="1" type="EL1018" name="D2"/>
<slave idx="2" type="EL1018" name="D3"/>
<slave idx="3" type="EL2008" name="D4"/>
<slave idx="4" type="EL2008" name="D5"/>
<slave idx="5" type="EL2084" name="D6"/>
<slave idx="6" type="EL2022" …
```
=> feat(lcec_configgen): Add a new tool that can auto-generate XML files based on installed EtherCAT hardware

src/devices/lcec_ax5100.c, src/devices/lcec_ax5200.c, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_rtec.c, src/lcec.h, src/lcec_ethercat.c
On devices with lots of PDOs (especially multi-axis CiA 402 devices), it's easy to overfill the sync structures, and there was previously no error checking at all, leading to memory corruption and weird bugs.
Issue #327
=> fix(syncs): Add error checking on sync size

debian/control, src/Makefile
The Debian build environment doesn't have Go installed, so this fails.  Disabling for now.  You can still build it manually.
=> fix(build): Temporarily stop building lcec_configgen

src/configgen/lcec_configgen.go, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_rtec.c, src/tests/test_cia402.c, src/tests/tests.h, tests/scottlaird-lcectest1/fulltest.hal, tests/scottlaird-lcectest1/fulltest.xml
This is enough to get my Leadshine 2CS3E-D507 "working", which is to say that I can use `basic_cia402` and `lcec_configgen` to produce a config that doesn't crash and shows approximately the correct set of HAL pins.
There are lots of tiny fixes here, including several CoE objects with the wrong addresses.
Issues #327 #180
=> fix(cia402): Get multi-axis partly working

debian/control, src/Makefile
Reverts linuxcnc-ethercat/linuxcnc-ethercat#332
=> fix(lcec_configgen): Re-enable building lcec_configgen now that the build farm has been updated

src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/lcec.h, src/lcec_ethercat.c, tests/scottlaird-lcectest1/fulltest.hal, tests/scottlaird-lcectest1/fulltest.xml
The CiA 402 library creates an *enormous* number of PDOs, especially on multi-axis devices, and the bulk of these aren't really things that need to be frequently changed.  This include details like `motor-rated-torque` and `home-method`, which *could* be `<modParam>`s that are unlikely to change at runtime, along with a few other settings that could reasonably be changed from time to time, but will never be updated on a millisecond-by-millisecond basis.
IMO, the UX for HAL pins is better than the UX for `<modParam>`s, as HAL pins are trivially discoverable, while `<modParam>`s just lurk in the documentation.  Plus, during setup and tuning, it's nice to be able to adjust peak RPM, motor current, etc on the fly.
The problem is that we can easily create more PDOs from pins than some devices …
=> fix(cia402): Move most non-performance critical write PDOs to SDOs

src/configgen/lcec_configgen.go, tests/scottlaird-lcectest1/fulltest.xml
This cleans up the generated configs for `generic` a bit.  We don't emit `gap` entries any more, as there's no real point.  This also tries to fix duplicate hal pin names; when it find duplicates, it prepends the last word of the PDO's comment onto the HAL pin name.  This works on all 3 unknown generic devices that I have right now.  2 of the 3 produce reasonable pin names, while the other is kind of dumb but functional.
=> fix(lcec_configgen): Remove bad "gap" entries and fix some duplicate names

src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_class_cia402_opt.h
I'm a bit worried that this is approaching the debuggability event horizon, but I *know* that we're over the "keep 13 lists consistent" event horizon, which is demonstrated by the number of items that were not, in fact, in all of the lists that they were supposed to be here.
=> style(cia402): Get rid of the giant lists of pin/PDO/etc initialization and replace with more macros

src/configgen/lcec_configgen.go, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_class_cia402_opt.h, src/devices/lcec_rtec.c, src/lcec_conf.c, tests/scottlaird-lcectest1/fulltest.xml
As mentioned in #343, it's completely possible (and in fact annoyingly easy) to create a config that tries to map more CiA 402 PDO entries than the hardware can actually support.  Leadshine and Delta, for example, only allow 8 entries per PDO.
I've mostly mitigated this for writable PDOs, but readable ones are still a mess.  A naive config for a Leadshine 2CS3E-D507 currently has 15 or 16 read PDO entries, vs a hardware limit of 8.  Annoyingly, this wasn't actually *failing*, it just failed to work properly, making debugging difficult.
This PR does a few things:
- (In `basic_cia402`) Adds `ciaRxPDOEntryLimit` and `ciaTxPDOEntryLimit` modparams.  This is the maximum number of PDO entries that the CiA 402 code will try to add per PDO.  They default to 8, which is annoyingly common.
- Adds …
=> fix(cia402): Add PDO entry limits, and modparams to adjust them

src/devices/lcec_class_cia402.c, tests/scottlaird-lcectest1/fulltest.xml
Cut-and-paste error; if you enable dout but not din things break.
=> fix(cia402): fix din/dout mistake

src/devices/lcec_deasda.c
1.26.1 didn't trigger a build on OBS, so pushing a new version to see if that fixes things.
=> fix(deasda): trivial change to force a build of 1.26.2

src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_class_cia402_opt.h, tests/scottlaird-lcectest1/cia402-all.xml
This fixes a couple problems.  First, a bunch of the VL-mode params don't match what my MX2 expects to see.  A couple were the wrong size, and a couple are actually ratios and need extra code.  Switched to modparams for now for those, although I guess we could do floats if we really wanted to.  Hmm. 
Second, somehow in the middle of refactoring, I completely stopped registering readable PDOs.  The first symptom is that `opmode-display` was always 0.  This should be fixed now.
Issue #180
=> fix(cia402): Actually make reading from PDOs work, and fix VL mappings

src/Makefile, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_ax5.c, src/devices/lcec_class_dout.c, src/devices/lcec_class_enc.c, src/devices/lcec_deasda.c, src/devices/lcec_dems300.c, src/devices/lcec_el2521.c, src/devices/lcec_el70x1.c, src/devices/lcec_el7211.c, src/devices/lcec_em7004.c, src/devices/lcec_epocat.c, src/devices/lcec_omrg5.c, src/devices/lcec_ph3lm2rm.c, src/devices/lcec_stmds5k.c, src/lcec.h, src/lcec_devicelist.c, src/lcec_ethercat.c, src/lcec_main.c
This is part of a set of PRs to make LCEC compliable with a C++ compiler.  The goal isn't to move LCEC to C++, but rather to be able to make use of C++'s generally-better error checking tools.
This fixes a bunch of minor issues around `lcec_param*` functions expecting `lcec_pin*` parameters but then interpreting them as `hal_param*`.  This is mostly workable in C, but results in the possibility of subtle errors.  This splits the two cases apart so we can enforce types better and catch problems.
=> refactor: switch lcec_param* to use param types instead of pin types

scripts/sdos.sh
Small script that wraps `ethercat sdos` and dumps the current value of all SDOs listed.
Kind of slow, but useful.
=> chore: add sdos.sh

src/devices/lcec_basic_cia402.c, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, tests/scottlaird-lcectest1/cia402-all.hal, tests/scottlaird-lcectest1/cia402-all.ini, tests/scottlaird-lcectest1/cia402-all.xml
This includes a handful of small fixes needed to get CSP working for my CiA 402 test devices, plus a set of config files.
The most important change is a bunch of `dcConf` tags in the XML; it's *amazing* how painful that was to catch.  There's also a change to allow CiA 402 devices to use non-consecutive PDO numbers.  Weirdly, the ECR60x2 has 0x1600, 0x1610, etc, but not 0x1601.
=> fix(cia402): Assorted bugfixes to get CSP working

src/devices/lcec_ax5100.c, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_ain.c, src/devices/lcec_class_ain.h, src/devices/lcec_class_aout.c, src/devices/lcec_class_aout.h, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_class_cia402_opt.h, src/devices/lcec_class_din.c, src/devices/lcec_class_dout.h, src/devices/lcec_deasda.c, src/devices/lcec_el1918_logic.c, src/devices/lcec_el41x2.c, src/devices/lcec_epocat.c, src/devices/lcec_ph3lm2rm.c, src/devices/lcec_stmds5k.c, src/lcec.h, src/lcec_conf.c, src/lcec_ethercat.c, src/lcec_main.c, src/lcec_malloc.c
We've had some drift vs clang-format's output.  I thought I'd re-ran this against the malloc change, but apparently not.
This should *only* include changes from running `clang-format -i` against src/*.[ch] and src/devices/*.[ch].
=> style: re-apply clang-format

documentation/rtec.md, src/devices/lcec_rtec.c, tests/scottlaird-lcectest1/cia402-all.hal, tests/scottlaird-lcectest1/cia402-all.xml
This starts bringing the `rtec` driver up to date WRT the current `basic_cia402` driver.
With this patch, both the ECT60 and ECR60x2 seem to be working, although I haven't done extensive testing.
This also adds a default `dcConf` config for these devices, equal to:
```
<dcConf assignActivate="300" sync0Cycle="*1" sync0Shift="0"/>
```
Thanks to that, this *should* be enough to work:
```
<slave idx="27" type="ECT60" name="rt-ect60"/>
```
By default, these map all of the PDO entries needed for CSP support.  This can be changed via a bunch of  `enable` modParams, but I'd like something a bit more user-friendly if possible.
Issue #180
=> feat(rtec): Re-sync RTelligent stepper driver with core CiA 402 code and add features

documentation/rtec.md, scripts/sync-sdos.sh, src/Makefile, src/configgen/devicelist.go, src/configgen/drivers/drivers.go, src/configgen/lcec_configgen.go, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_class_cia402_opt.h, src/devices/lcec_rtec.c, src/lcec.h, src/lcec_devices.c, src/lcec_main.c, src/lcec_modparam.c, src/tests/test_cia402.c, src/tests/test_modparam.c, tests/scottlaird-lcectest1/cia402-all.hal
This adds two fields to `lcec_modparam_desc_t`, the structure that describes `<modParam>` options in LCEC.  These are both optional, and are used for communicating with `lcec_configgen` or other configuration systems.
The first field, `config_value`, shows a default value for the modParam.  This should (but does not have to) match the default of the system.  Any modParam that has `config_value` set will appear in `lcec_configgen`'s output; see below for an example.
The second field, `config_comment` provides a comment to go with the modParam.
This PR modifies `lcec_rtec`'s `enableCSP`'s `config_value` to `true` and sets its `config_comment` to `Enable support for Cyclic Synchronous Position mode.`.  When `lcec_configgen` runs and finds a RTEC device, then it'll produce output like this: …
=> feat(configgen): propagate modparams to lcec_configgen

src/devices/lcec_basic_cia402.c, src/devices/lcec_deasda.c, src/lcec_conf_util.c
This fixes a couple minor C++ compilation bugs that have crept in, plus an obsolete comment in `lcec_basic_cia402.c`.
I try to keep this code C++-clean, as C++ compilers are *generally* stricter about type mismatches and catch bugs that are *technically* legal C but still incorrect.
I also use clang's `scan-build` and GCC's `-fanalyzer` from time to time.  They all find bugs.
=> fix: fix minor C++ compile bugs

src/configgen/drivers/drivers.go, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/devices/lcec_leadshine_stepper.c, src/devices/lcec_rtec.c, src/tests/test_cia402.c
There's a moderate amount of magic under the hood with `<modParam>`s for CiA 402 devices.  Since devices can have between 1 and 8 motor channels (axes) per device, we need a way to specify per-channel modParams without needing to duplicate everything 8x.  To do this, we auto-generate an expanded list of modParams in `lcec_cia402_modparams()`, with one per channel.  
Previously, we always generated a full set of per-channel modParams plus the base-named model for all CiA 402 devices.  That is, when there was a per-channel modParam named `foo`, we created a list that included `foo`, `ch1foo`, `ch2foo`, ... `ch8foo`.
That was fine until we started adding documentation for things; once that happened, if we added docs for per-channel modParams then we'd *always* get 9 sets of comments …
=> feat(cia402): Allow for variable numbers of channels in modParam generation

src/devices/lcec_leadshine_stepper.c
This is sort of an experiment; the `lcec_typelist_t` struct is getting big, and initializing all of the items in order (half of which are NULL or 0) is ugly.  This switches `leadshine_stepper` to use C [designated initializers](https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html), which are a C99 feature.  I don't think I've seen any elsewhere in LCEC, but (for example) the Linux kernel is full of them, so they're not exactly a weird corner case of the language.
The `TYPEDEFAULTS` macro here annoys me.  I *could* merge a default together with the provided values later (in `ADD_TYPES*`, presumably), but that's not an improvement.   The only obvious improvement that I can see would be to turn each device type declaration into an instantiation of a C++ class.  We could probably make …
=> fix(leadshine_stepper): simplify type list

documentation/pdos-and-syncs.md, src/devices/lcec_basic_cia402.c, src/devices/lcec_class_cia402.c, src/devices/lcec_class_cia402.h, src/lcec.h, src/lcec_ethercat.c, tests/scottlaird-lcectest1/cia402-all.xml
This adds optional support for "autofill"ing PDO entries.  When it is enabled (via a call to `lcec_syncs_enable_autoflow()`), we will check to see if the current PDO is full and automatically create a new PDO as needed to permit mapping PDO entries.
This is needed for the Omron MX2, as it only allows 2 (!) PDO entries per PDO, but seems to support 512 (!) PDOs.  So we set it up with autofill on and tell it to cap PDOs at 2 entries, and it ends up creating a bunch of tiny little 2-entry PDOs.
Issues: #180 #414
=> feat(syncs): Support overflowing PDOs when all PDO entries are in use

documentation/DEVICES.md, documentation/devices/OMMX2.yml, documentation/index.md, documentation/ommx2.md, src/configgen/drivers/drivers.go, src/devices/lcec_ommx2.c, tests/scottlaird-lcectest1/cia402-all.xml
A very quick, basic driver for the Omron MX2.
This uses the new PDO "autofill" setting (see #417), without that I don't think my revision of the MX2 would work at all.
One thing to notice--this doesn't use distributed clocks.  It doesn't look like the MX2 supports them.  Or, at least the manual implies that they don't.
I haven't really *used* this yet, but it probes successfully.  
Issue #414
=> feat(ommx2): Add Omron MX2 VFD driver

documentation/leadshine_stepper.md, src/devices/lcec_leadshine_stepper.c
Add docs on how to change Leadshine digital input pins from their pre-defined functions.  Also, change the numbering for `din-X` ports to start at 1, so the HAL pin numbers match the names on the device.
Issue #327
=> fix(leadshine_stepper): Fix din numbers and document how to change input port settings

src/configgen/drivers/drivers.go, src/devices/lcec_deasda.c
This adds `<modParam name="enableDigitalOut" value="false"/>` for Delta ASDA-series drives.  Some devices don't support digital outs and crash when they're accessed.
Issue #372
=> fix(deasda): Add a modparam to disable digital out

src/devices/lcec_class_din.c, src/devices/lcec_class_dout.c, src/devices/lcec_leadshine_stepper.c, tests/scottlaird-lcectest1/cia402-all.xml
Digital in wasn't working for the Leadshine stepper driver for a couple reasons.
With this, I've verified that I'm able to receive signals via digital inputs.  Outputs are still untested.
#327
=> fix(leadshine_stepper): fix din bugs

src/Makefile, src/lcec_main.c
This has been bugging me a while; if we crash (which can happen a lot during debugging), then we don't have any sort of stack backtrace or any easy way to know where things crashed.  Yeah, you can attach a debugger or add lots of print statements, but a simple stack backtrace is frequently good enough.  So here we go.
This dumps a stack backtrace using `glibc`'s built-in stack backtrace handler.  It's not perfect, in that it doesn't seem to find the symbols from `lcec.so`, but it's still helpful.  Here's a recent crash of mine:
```
-- STACK TRACE START
0       /usr/lib/linuxcnc/modules/lcec.so(+0xfc7c) [0x7f2612ae6c7c]
1       /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f2613541050]
2       /lib/x86_64-linux-gnu/libc.so.6(+0x15543f) [0x7f261365a43f]
3 …
```
=> feat(main): Show stack backtrace on failure

.github/workflows/ci.yml
Upgrade CI jobs from Ubuntu 20.04 to 22.04; this seems to fix the GCC build problem that was breaking CI checks.
=> chore: fix CI environment

.github/workflows/ci.yml, src/configgen/drivers/drivers.go, src/devices/lcec_ep9214.c, tests/scottlaird-lcectest1/fulltest.xml
This is an initial pass at a driver for the [Beckhoff EP9214](http://beckhoff.com/EP9214) power-delivery module.  It reports back status and lets you control fusing/circuit breaking.  The Beckhoff EP9224 is similar; I may end up extending this to cover both devices, or I may do the 9224 in its own driver.  I haven't decided yet.
The EP92x4 devices take in 24V power over a large 7/8" connector and use that to power 4 M12 connectors, each of which can power a chain of EP-series modules.  The EP9214 can set custom current limits for both the Us and Up lines for each connector, as well as flag a number of error conditions.  The EP9224 adds current measurement and a few other metrics.
Issue #31
=> feat(ep9214): Create driver for Beckhoff EP9214

documentation/configuration-reference.md, documentation/distributed-clocks.md, examples/generic-complex/ethercat-conf.xml, examples/omrg5/omrg5.xml, examples/swm-fm45a/ethercat-conf.xml, src/lcec.h, src/lcec_conf.c, src/lcec_conf.h, src/lcec_main.c
This PR adds an explicit master configuration option `syncServoPeriodToRefClock="true|false"`,
reference documentation for configuration and detailed description in distributed-clocks.md.
The option is also added to three of the examples.
The actual functionality to synchronize LinuxCNC's servo thread with DC is already in the code.
It is activated by using a negative value of the `refClockSyncCycles`. This wasn't described anywhere.
There are many users in the linuxcnc forum that encounter the consequences of this unsynchronization,
myself included. Gravel sound, friction sound, acceleration and torque peaks can be seen from 
drives synced by DC. This is caused by interference between the different speed clocks.
This option is so important it deserves an own option. 
Having it as part of …
=> Synchronize DC and LinuxCNC servo-thread explicit option and documentation
