- documentation/DEVICES.md
- documentation/devices/EL1018.yml
- documentation/devices/EL1808.yml
- documentation/devices/EL2008.yml
- documentation/devices/EL2808.yml
- documentation/devices/EL3162.yml
- documentation/devices/EL3202.yml
- documentation/devices/EL3403.yml
- documentation/devices/EL6090.yml
- documentation/devices/EM3702.yml
- documentation/devices/EP1008.yml
- documentation/devices/EP1018.yml
- documentation/devices/EP2338.yml
- documentation/devices/EP7041.yml
- scripts/devicetable/devicetable.go
Quick update to list which devices I have.  I'd be good to have at least one person listed per device, for help with testing.
> Documentation update to list the devices that @scottlaird has on hand.

- .github/workflows/release.yml
This will probably do something dumb, but it's a work in progress.
> Run Debian release jobs on all builds

- .github/workflows/release.yml
> release: update opensuse install line

- .github/workflows/release.yml
- debian/changelog
> release: *actually* remove the deb releases that the previous PR was supposed to remove.

- CONTRIBUTING
Add additional details about Conventional Commits to the CONTRIBUTING file.
Issue #7
> docs: Update CONTRIBUTING

- .github/workflows/release.yml
Not at all sure that this is the right fix, but trying to head the right direction.
> fix(test): Run the Debian changelog more aggressively.

- .github/workflows/release.yml
> fix(test): Use the correct syntax for CURRENT_VERSION in release.yml

- .github/workflows/release.yml
Too much networking, it must be bgp, right?
Issue: #36
> ci: it's gbp dch, not bgp dch.

- .github/workflows/debian.yml
Mostly just testing the release pipeline.
Issue: #36
> fix(test): Add --quiet to a few more 'apt install' calls

- .github/workflows/release.yml
Apparently steps.release.output.changelog isn't set; try steps.release.outputs.version?
Issue: #36
> fix(test): try something different to see if a new release was created

- .github/workflows/debian.yml
- .github/workflows/release.yml
This still leaves issues with that workflow not running automatically.
Issue: #36
> fix(test): Move the changelog updater to the Debian release workflow

- .github/workflows/debian.yml
> fix(test): Show github context before running changelog action

- .github/workflows/ci.yml
- .github/workflows/debian.yml
- .github/workflows/release.yml
- node_modules/.package-lock.json
- node_modules/punycode/LICENSE-MIT.txt
- node_modules/punycode/README.md
- node_modules/punycode/package.json
- node_modules/punycode/punycode.es6.js
- node_modules/punycode/punycode.js
- package-lock.json
- package.json
This is probably pointless at our scale, but it'll add a small amount of
consistency.
> ci: enable merge queues

- documentation/devices/EK1100.yml
- documentation/devices/EK1110.yml
- documentation/devices/EL1018.yml
- documentation/devices/EL1904.yml
- documentation/devices/EL2008.yml
- documentation/devices/EL2022.yml
- documentation/devices/EL2034.yml
- documentation/devices/EL2084.yml
- documentation/devices/EL2798.yml
- documentation/devices/EL2904.yml
- documentation/devices/EL6900.yml
I'm building a test system for verifying that LCEC works on actual
hardware before committing any of the refactoring PRs that are in
flight.
Issue #77
> docs: Documentation updates for testing

- src/realtime.mk
This is basically https://github.com/sittner/linuxcnc-ethercat/pull/122
and https://github.com/LinuxCNC/linuxcnc/pull/2610
manually merged.
Should fix https://github.com/sittner/linuxcnc-ethercat/issues/123
> build: update realtime.mk to fix ecrt_slave_config_sdo error

- examples/testbench/README.md
- examples/testbench/haltest.sh
- examples/testbench/testbench-init.hal
- src/realtime.mk
This matches hardware that I have on hand for testing, and
includes a shell script that can verify basic functionality.
Issue #77
> ci: Add a set of "testbench" examples with a test script

- src/realtime.mk
Somehow I dropped this in a fit of mis-merging changes.
From https://github.com/sittner/linuxcnc-ethercat/pull/122
> build: Re-add EXTRA_LDFLAGS

- documentation/DEVICES.md
- documentation/devices/EL1018.yml
- documentation/devices/EL2008.yml
> docs: Update device table with support status

- documentation/DEVICES.md
- scripts/devicetable/devicetable.go
> docs: Fix plural/singular issue

- README.md
> docs: update README.md to mention devices/

- CONTRIBUTING.md
> docs: Formatting fix for CONTRIBUTING.md

- src/devices/lcec_epocat.c
- src/devices/lcec_epocat.h
- src/lcec.h
feat(epocat): Add EpoCAT FR4000
From https://github.com/sittner/linuxcnc-ethercat/pull/120
Issue #86
feat(epocat): Modify lcec_epocat.[ch] to fit new style
Issue #86
build: reformat epocat code
First try at running clang-format
> feat(epocat): Add EpoCAT FR4000

- scripts/devicelist/devicelist.go
> build: update devicelist.go to work with devices/

- documentation/DEVICES.md
- documentation/devices/EPOCAT.yml
> docs: Add epocat to device table

- documentation/DEVICES.md
- documentation/devices/EX260_SEC1.yml
- documentation/devices/EX260_SEC2.yml
- documentation/devices/EX260_SEC3.yml
- documentation/devices/EX260_SEC4.yml
- src/devices/lcec_ex260.c
- src/devices/lcec_ex260.h
- src/lcec.h
From https://github.com/sittner/linuxcnc-ethercat/pull/103, by @satiowadahc
fixes #97
> feat(ex260): Add support for SMC EX-260

- src/devices/lcec_generic.c
fixes https://github.com/sittner/linuxcnc-ethercat/issues/116
> fix(generic): Write floating point values correctly

- documentation/DEVICES.md
I forgot to re-run the script after the last change.
> docs: Update device table again

- .clang-format
- src/devices/lcec_el3xxx.c
- src/devices/lcec_el3xxx.h
This was making things crash sometimes.
> fix(eel3xxx): remove sync pin read from el30xx

- src/devices/lcec_epocat.c
Result of running `clang-format -i lcec_epocat.[ch]`
Issue #135
> build: reformat lcec_epocat.c

- src/devices/lcec_epocat.c
> fix(epocat): update EpoCAT code to drop FR1000 and add FR4000 support

- examples/testbench/ethercat.xml
- examples/testbench/haltest.sh
- examples/testbench/test1-ethercat.xml
- examples/testbench/test1.hal
- src/lcec_conf.c
> fix(lcec_conf): Stop segfaulting on incorrect type= in XML

- documentation/DEVICES.md
- documentation/devices/EJ3004.yml
- documentation/devices/EJ3202.yml
- documentation/devices/EJ3214.yml
- documentation/devices/EJ5002.yml
- documentation/devices/EL3201.yml
- documentation/devices/EL3204.yml
- documentation/devices/EL3208.yml
- documentation/devices/EL3214.yml
- documentation/devices/EL3218.yml
- documentation/devices/EL5032.yml
- documentation/devices/EL5101.yml
- documentation/devices/EL5151.yml
- documentation/devices/EL5152.yml
- documentation/devices/EL7041_1000.yml
- documentation/devices/EP3174.yml
- documentation/devices/EP3184.yml
- documentation/devices/EP3204.yml
- scripts/devicelist/devicelist.go
Also fix a few old consistency problems.
> docs: update device documentation for new devices

- tests/haltest.sh
- tests/test2.xml
Update hal tests to clean up a bit of shell, and also add an extra test for the EL3403.
> test: update

- documentation/adding-drivers.md
> docs: Create an "adding-drivers" doc.

- src/devices/lcec_class_din.c
- src/devices/lcec_class_din.h
- src/devices/lcec_el1xxx.c
> refactor: add lcec_din_read_all

- .github/workflows/pages.yml
> docs: Fix doxyfile-path param

- .doxyfile
- src/devices/lcec_el1252.c
- src/devices/lcec_el1859.c
- src/devices/lcec_el1xxx.c
- src/devices/lcec_el3xxx.c
- src/devices/lcec_ep2316.c
- src/devices/lcec_generic.c
- src/lcec.h
- src/lcec_devicelist.c
- src/lcec_ethercat.c
- src/lcec_main.c
- src/lcec_pins.c
This is starting to look reasonable at this point.  We still need a lot of annotation work, but it can probably happen organically.
Issue #194
> docs: Add additional doxygen annotations

- src/lcec_main.c
> chore(main): Fail if drivers fail to call LCEC_PDO_INIT() for each PDO.

- documentation/DEVICES.md
- documentation/devices/EK1818.yml
- documentation/devices/EK1828-0010.yml
- documentation/devices/EK1828.yml
- documentation/devices/EPP2316.yml
- documentation/devices/generic.yml
- scripts/devicelist/devicelist.go
Easier than I expected. 
Closes #221
> docs: Update devicelist to use lcec_devices

- src/devices/lcec_el1859.c
I'm still not quite happy with the way this looks, experimenting to see what works.
> refactor(el1859): find reasonable style for EL1859

- README.md
- documentation/configuration-reference.md
Quick take on docs for generic devices.
> docs: Add generic docs

- documentation/DEVICES.md
- documentation/devices/EL3124.yml
- documentation/devices/EasyIO.yml
- src/devices/lcec_easyio.c
*Completely* untested, as I don't have the hardware.  But I wanted to see what a combined ain/aout/din/dout board would look like with `class_din` and friends.
Issue #158
> feat(easyio): Create easyio driver, completely untested.

- src/tests/test_lookup.c
Add a few comments to make this more readable.
> test: slight cleanups on test_lookup.c

- src/lcec_main.c
Add an additional check to make sure that devices always register the number of PDO entries that they claimed in their `lcec_typelist_t` definition.  We previously checked that drivers used all of the PDOs that they'd requested, but we didn't catch the opposite case where drivers overflowed the `pdo_entry_regs` array.  We now catch both cases.
> fix(main): Detect over-registering of PDO entries

- src/devices/lcec_easyio.c
This should fix https://forum.linuxcnc.org/ethercat/51565-git-update-1-14-3#292222
> fix(easyio): Finish initializing analog out ports

- documentation/devices/DeASDA3.yml
fixed web link in documentation for Delta A3
just a cosmetic fix
no issue
> Update web link for DeASDA3.yml

- documentation/devices/DeASDB3.yml
fixed web link and PID in documentation for Delta B3
just a cosmetic fix
no issue
> Update web link and PID for DeASDB3.yml

- documentation/deasda.md
> docs: Fix deasda XML

- documentation/index.md
- documentation/pdos-and-syncs.md
This has been bugging me for a while--why do different drivers approach setting up PDOs so differently?
> docs: Add PDO and Sync discussion doc

- src/Makefile
- src/lcec.h
- src/lcec_modparam.c
- src/tests/test_modparam.c
- src/tests/tests.h
Breaking code out of the CiA 402 PR that is needed for CiA 402, but isn't really CiA 402-specific.
> chore: Create modparam utility functions

- src/devices/lcec_basic_cia402.c
- src/devices/lcec_class_cia402.c
- src/devices/lcec_class_cia402.h
- src/devices/lcec_rtec.c
> feat(cia402): Add modparams for enabling `enable_` options

- src/configgen/lcec_configgen.go
Working to get multi-axis working.  This is enough to get `lcec_configgen` to see both my Leadshine and Rovix devices and generate a passable config for them.
> fix(lcec_configgen): Recognize devices with no name set and add multi-channel CiA 402 support

- debian/control
- src/Makefile
Reverts linuxcnc-ethercat/linuxcnc-ethercat#334
Issue #336
> fix(build): Disable lcec_configgen again

- debian/control
- src/Makefile
- src/configgen/vendor/gopkg.in/yaml.v3/LICENSE
- src/configgen/vendor/gopkg.in/yaml.v3/NOTICE
- src/configgen/vendor/gopkg.in/yaml.v3/README.md
- src/configgen/vendor/gopkg.in/yaml.v3/apic.go
- src/configgen/vendor/gopkg.in/yaml.v3/decode.go
- src/configgen/vendor/gopkg.in/yaml.v3/emitterc.go
- src/configgen/vendor/gopkg.in/yaml.v3/encode.go
- src/configgen/vendor/gopkg.in/yaml.v3/go.mod
- src/configgen/vendor/gopkg.in/yaml.v3/parserc.go
- src/configgen/vendor/gopkg.in/yaml.v3/readerc.go
- src/configgen/vendor/gopkg.in/yaml.v3/resolve.go
- src/configgen/vendor/gopkg.in/yaml.v3/scannerc.go
- src/configgen/vendor/gopkg.in/yaml.v3/sorter.go
- src/configgen/vendor/gopkg.in/yaml.v3/writerc.go
- src/configgen/vendor/gopkg.in/yaml.v3/yaml.go
- src/configgen/vendor/gopkg.in/yaml.v3/yamlh.go
- src/configgen/vendor/gopkg.in/yaml.v3/yamlprivateh.go
- src/configgen/vendor/modules.txt
So, vendoring in go seems surprisingly easy.  `go mod vendor`, and you're done.  If it works...
Issue #336
> fix(build): Yet another attempt to get lcec_configgen to build

- src/configgen/lcec_configgen.go
- src/devices/lcec_basic_cia402.c
- src/devices/lcec_class_cia402.c
- src/devices/lcec_class_cia402.h
- src/devices/lcec_class_din.h
- src/devices/lcec_class_dout.h
- src/devices/lcec_rtec.c
- tests/scottlaird-lcectest1/fulltest.xml
Add generic Digital In/Digital Out support to CiA 402.
Closes #348
> feat(cia402): Add din/dout support to CiA 402

- src/configgen/lcec_configgen.go
- src/devices/lcec_class_cia402.c
- src/devices/lcec_class_cia402.h
- src/devices/lcec_class_cia402_opt.h
- tests/scottlaird-lcectest1/fulltest.xml
I think this is everything that I have planned for this phase of CiA 402 work.  See cia402.md .
Closes #349
> feat(cia402): Add the last remaining pins and modparams

- src/devices/lcec_class_cia402.h
- src/devices/lcec_class_cia402_opt.h
> fix(cia402): Move 2 more pins from PDOs to SDOs

- src/devices/lcec_class_cia402.c
- tests/scottlaird-lcectest1/fulltest.hal
- tests/scottlaird-lcectest1/fulltest.xml
Also changes my test XML and HAL somewhat.
Issue #343.
> fix(cia402): Remove debugging statements, and add one required pin to `csv`.

- src/devices/lcec_el2xxx.c
Added EL2624 to lcec_el2xxx.c and tested on EL2624
> feat(el2624): Add support for Beckhoff EL2624

- src/Makefile
> build: Fix hanging build issue

- src/devices/lcec_deasda.c
This is untested, but *should* add digital output support for Delta ASDA devices.  This adds 4 outputs named 'dout-d0[1234]'.  I haven't checked any of the ASDA manuals to see if various models have more or fewer outputs.
#372
> feat(deasda): Add digital output (untested)

- src/devices/lcec_deasda.c
> fix(deasda): dout should be 0x60fe, not 0x60f3

- src/devices/lcec_deasda.c
This makes digital outputs for Delta ASDA devices conditional on the model; at least some B3 devices appear to not have the SDO objects for digital output, although there's some confusion in the manual around this.
This moves the `deasda` driver from a static sync setup to a more dynamic style, as used in the `cia402` driver (and copied from `ax5100` and `ax5200`. 
Issue #372
> fix(deasda): Disable digital outputs on B3 devices

- documentation/changes.md
- documentation/index.md
Create a document for discussing breaking changes.  In general, we try to avoid user-visible breaking changes, but sometimes they're unavoidable, and other times we believe that the number of impacted users is so small (ideally 0) that breaking things is acceptable.  We would like to keep a record of these changes for future review and debugging.
> docs: Add changes.md, listing breaking changes

- documentation/pdos-and-syncs.md
Fix a few issues pointed out in #381.
> docs: Update PDO doc

- src/devices/lcec_basic_cia402.c
- tests/scottlaird-lcectest1/cia402-all.hal
- tests/scottlaird-lcectest1/cia402-all.xml
> fix(cia402): Fix ciaTxPDOEntryLimit param

- src/lcec.h
Fixes #396, and is also needed for #328.
> fix: Increase the number of PDOs allowed per device from 128 to 256

- documentation/distributed-clocks.md
- documentation/index.md
Add basic distributed clock docs
> docs: Add distributed clocks documentation

- documentation/leadshine_stepper.md
Write documentation for Leadshine stepper outputs, and make minor tweaks to the input documentation.
At this point, I can write to the `dout` pins and everything looks like it's working (0x60fe:01 gets updated, 0x2155:0 gets updated), but I'm not reading anything interesting on the output pins.  The digital output portion of Leadshine's docs say "the power supply is provided by the user, and if the polarity of the power supply is reversed it will damage the drive".  Life would be so much easier if they could just provide +24V on the output pins like Beckhoff does.
At some point I'll wire something up here and actually test it, but today's not a great day on the "concentrate enough to not fry your drive by accident" front.  I can't see any voltage between O1/O2/O3/O4 and COM-, which fits …
> docs: Update leadshine stepper digital i/o docs

- src/configgen/drivers/drivers.go
- src/devices/lcec_omr1s.c
This adds support for Omron's new 1S servo drives.
Issue: #440
> feat(omron-1s): Add support for Omron 1S servo series
